# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='权限名称')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='会员名称')),
                ('level', models.IntegerField(default=0, verbose_name='会员等级')),
                ('price', models.FloatField(default=0.0, verbose_name='当前会员对应的价格')),
                ('days', models.IntegerField(default=0, verbose_name='购买的天数')),
            ],
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='会员的ID')),
                ('perm_id', models.IntegerField(verbose_name='权限的ID')),
            ],
        ),
    ]
