# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_expired',
            field=models.DateTimeField(default='2000-1-1', verbose_name='会员过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的VIP'),
        ),
    ]
