# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190924_1637'),
    ]

    operations = [
    ]
